---
#
# Docker Dependencies
#

- name: Install Docker (Debian Family).
  block:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      changed_when: false

    - name: Install Docker Package
      apt:
        name: ['docker.io', 'python3-docker', 'python3-dockerpty']
        state: present
  when: ansible_os_family == 'Debian'

- name: Install Docker (RedHat).
  block:
    - name: Install Yum Repo Tools
      yum:
        name: ['yum-utils', 'device-mapper-persistent-data', 'lvm2']
        state: present

    - name: Install Docker Packages (RedHat).
      yum:
        name: ['docker.io']
        state: present
  when: ansible_os_family == 'RedHat'
